//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mastery
    {
        public int MasterId { get; set; }
        public int Poziom { get; set; }
        public int Capacity { get; set; }
        public Nullable<int> AktywnaMisjaId { get; set; }
    }
}
