//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Misje
    {
        public int MisjaId { get; set; }
        public int TypMisji { get; set; }
        public int PozycjaOdbioruId { get; set; }
        public int PozycjaDostarczeniaId { get; set; }
        public int PaletaId { get; set; }
        public int MasterId { get; set; }
        public int Status { get; set; }
    }
}
