//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Palety
    {
        public int PaletaId { get; set; }
        public string Oznaczenie { get; set; }
        public string KodKreskowy { get; set; }
        public string NazwaProduktu { get; set; }
        public int Stan { get; set; }
        public string NumerPartiiProdukcyjnej { get; set; }
        public System.DateTime DataProdukcji { get; set; }
        public System.DateTime TerminPrzydatnosci { get; set; }
        public string Destynacja { get; set; }
    }
}
