//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartiePalety
    {
        public int PaletaId { get; set; }
        public string Oznaczenie { get; set; }
        public string KodKreskowy { get; set; }
        public int PartiaId { get; set; }
        public int StateId { get; set; }
    
        public virtual Partie Partie { get; set; }
    }
}
