//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partie()
        {
            this.PartiePalety = new HashSet<PartiePalety>();
        }
    
        public int PartiaId { get; set; }
        public string NumerPartii { get; set; }
        public int ProduktId { get; set; }
        public System.DateTime DataUtworzenia { get; set; }
        public int IloscPalet { get; set; }
    
        public virtual Produkty Produkty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartiePalety> PartiePalety { get; set; }
    }
}
