//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozycje
    {
        public int PozycjaId { get; set; }
        public int Szerokosc { get; set; }
        public int Wysokosc { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Poziom { get; set; }
        public int Typ { get; set; }
        public Nullable<int> Przod { get; set; }
        public Nullable<int> Tyl { get; set; }
        public Nullable<int> Lewo { get; set; }
        public Nullable<int> Prawo { get; set; }
        public Nullable<int> Gora { get; set; }
        public Nullable<int> Dol { get; set; }
        public int AktualnyKierunek { get; set; }
        public string Zatoka { get; set; }
        public string Rampa { get; set; }
        public Nullable<int> MasterId { get; set; }
        public Nullable<int> PaletaId { get; set; }
        public bool PlcCommunication { get; set; }
    }
}
