//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SimulatorContext : DbContext
    {
        public SimulatorContext()
            : base("name=SimulatorContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Palety> Palety { get; set; }
        public virtual DbSet<Partie> Partie { get; set; }
        public virtual DbSet<PartiePalety> PartiePalety { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Pozycje> Pozycje { get; set; }
    }
}
