//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSimulator.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozycje
    {
        public int PozycjaId { get; set; }
        public int Szerokosc { get; set; }
        public int Wysokosc { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int TypPozycjiId { get; set; }
    }
}
