//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseSimulator.BazaDanych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        public int ProduktId { get; set; }
        public string Nazwa { get; set; }
        public int AktualnyKodKreskowy { get; set; }
        public int TerminPrzydatnosciWDniach { get; set; }
        public string Kolor { get; set; }
        public string Czcionka { get; set; }
    }
}
