//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simulator.Siemens
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alive
    {
        public int Id { get; set; }
        public long PlcCounter { get; set; }
        public long PcCounter { get; set; }
    }
}
